name: Feature Request
description: Suggest a feature
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: How should this work?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
      description: What other approaches did you consider?
